<a href="https://colab.research.google.com/github/Chris-Adigwe/Stage-3-quiz-workbook-for-Christopher-Adigwe/blob/master/Stage_3_Quiz_for_Christopher_Adigwe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np
import pandas as pd

In [22]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00471/Data_for_UCI_named.csv')
df.head()

tau1      tau2      tau3  ...        g4      stab     stabf
0  2.959060  3.079885  8.381025  ...  0.958034  0.055347  unstable
1  9.304097  4.902524  3.047541  ...  0.781760 -0.005957    stable
2  8.971707  8.848428  3.046479  ...  0.109853  0.003471  unstable
3  0.716415  7.669600  4.486641  ...  0.362718  0.028871  unstable
4  3.134112  7.608772  4.943759  ...  0.820923  0.049860  unstable

[5 rows x 14 columns]

In [23]:
df = df.drop('stab', axis=1)
df

tau1      tau2      tau3  ...        g3        g4     stabf
0     2.959060  3.079885  8.381025  ...  0.887445  0.958034  unstable
1     9.304097  4.902524  3.047541  ...  0.562139  0.781760    stable
2     8.971707  8.848428  3.046479  ...  0.839444  0.109853  unstable
3     0.716415  7.669600  4.486641  ...  0.929381  0.362718  unstable
4     3.134112  7.608772  4.943759  ...  0.656947  0.820923  unstable
...        ...       ...       ...  ...       ...       ...       ...
9995  2.930406  9.487627  2.376523  ...  0.813512  0.608385  unstable
9996  3.392299  1.274827  2.954947  ...  0.285880  0.366120    stable
9997  2.364034  2.842030  8.776391  ...  0.149286  0.145984    stable
9998  9.631511  3.994398  2.757071  ...  0.889118  0.818391  unstable
9999  6.530527  6.781790  4.349695  ...  0.378761  0.942631  unstable

[10000 rows x 13 columns]

In [24]:
df.head()

tau1      tau2      tau3  ...        g3        g4     stabf
0  2.959060  3.079885  8.381025  ...  0.887445  0.958034  unstable
1  9.304097  4.902524  3.047541  ...  0.562139  0.781760    stable
2  8.971707  8.848428  3.046479  ...  0.839444  0.109853  unstable
3  0.716415  7.669600  4.486641  ...  0.929381  0.362718  unstable
4  3.134112  7.608772  4.943759  ...  0.656947  0.820923  unstable

[5 rows x 13 columns]

In [29]:
x = df.drop('stabf', axis=1)
y = df['stabf']

In [30]:
#split the data into training and testing set 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state=1)

In [34]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)


x_test_scaled = scaler.fit_transform(x_test)

RandomForestClassifier

In [43]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=1)
rf.fit(x_train_scaled,y_train)
rf_predictions = rf.predict(x_test_scaled)

In [89]:
from sklearn.metrics import classification_report, recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
cnf_mat = confusion_matrix(y_true=y_test, y_pred=rf_predictions,labels=['stable', 'unstable'])
cnf_mat

array([[ 624,   88],
       [  56, 1232]])

In [117]:
accuracy = accuracy_score(y_true=y_test, y_pred=rf_predictions)
round(accuracy,4)

0.928

In [115]:
precision = precision_score(y_true=y_test, y_pred=rf_predictions, pos_label='stable')
precision

0.9176470588235294

In [49]:
recall = recall_score(y_true=y_test, y_pred=rf_predictions, pos_label='stable')
print('Recall: {}'.format(round(recall*100), 2))

Recall: 88.0


In [50]:
f1 = f1_score(y_true=y_test, y_pred=rf_predictions, pos_label='stable')
print('F1: {}'.format(round(f1*100), 2))

F1: 90.0


In [103]:
print('classification report for random forest', classification_report(y_test, rf_predictions))

classification report for random forest               precision    recall  f1-score   support

      stable       0.92      0.88      0.90       712
    unstable       0.93      0.96      0.94      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.92      0.92      2000
weighted avg       0.93      0.93      0.93      2000



XGBClassifier

In [63]:
from xgboost import XGBClassifier
xgb = XGBClassifier(random_state=1)
xgb.fit(x_train_scaled,y_train)
xgb_predictions = xgb.predict(x_test_scaled)

In [64]:
cnf_mat = confusion_matrix(y_true=y_test, y_pred=xgb_predictions,labels=['stable', 'unstable'])
cnf_mat

array([[ 599,  113],
       [  49, 1239]])

In [65]:
precision = precision_score(y_true=y_test, y_pred=xgb_predictions, pos_label='stable')
print('Precision: {}'.format(round(precision*100), 2))

Precision: 92.0


In [66]:
recall = recall_score(y_true=y_test, y_pred=xgb_predictions, pos_label='stable')
print('Recall: {}'.format(round(recall*100), 2))

Recall: 84.0


In [118]:
accuracy = accuracy_score(y_true=y_test, y_pred=xgb_predictions)
accuracy

0.919

In [68]:
f1 = f1_score(y_true=y_test, y_pred=xgb_predictions, pos_label='stable')
print('F1: {}'.format(round(f1*100), 2))

F1: 88.0


In [99]:
print('Classfication report for XGBOOST\n', classification_report(y_test, xgb_predictions))

Classfication report for XGBOOST
               precision    recall  f1-score   support

      stable       0.92      0.84      0.88       712
    unstable       0.92      0.96      0.94      1288

    accuracy                           0.92      2000
   macro avg       0.92      0.90      0.91      2000
weighted avg       0.92      0.92      0.92      2000



lightgbm

In [69]:
from lightgbm import LGBMClassifier
lgm = LGBMClassifier(random_state=1)
lgm.fit(x_train_scaled,y_train)
lgm_predictions = lgm.predict(x_test_scaled)

In [70]:
cnf_mat = confusion_matrix(y_true=y_test, y_pred=lgm_predictions,labels=['stable', 'unstable'])
cnf_mat

array([[ 635,   77],
       [  52, 1236]])

In [71]:
precision = precision_score(y_true=y_test, y_pred=lgm_predictions, pos_label='stable')
print('Precision: {}'.format(round(precision*100), 2))

Precision: 92.0


In [72]:
recall = recall_score(y_true=y_test, y_pred=lgm_predictions, pos_label='stable')
print('Recall: {}'.format(round(recall*100), 2))

Recall: 89.0


In [119]:
accuracy = accuracy_score(y_true=y_test, y_pred=lgm_predictions)
accuracy

0.9355

In [74]:
f1 = f1_score(y_true=y_test, y_pred=lgm_predictions, pos_label='stable')
print('F1: {}'.format(round(f1*100), 2))

F1: 91.0


In [100]:
print('Classification report for lgm \n', classification_report(y_test, lgm_predictions))

Classification report for lgm 
               precision    recall  f1-score   support

      stable       0.92      0.89      0.91       712
    unstable       0.94      0.96      0.95      1288

    accuracy                           0.94      2000
   macro avg       0.93      0.93      0.93      2000
weighted avg       0.94      0.94      0.94      2000



Extra Trees Classifier

In [76]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.model_selection import RandomizedSearchCV


hyperparameter_grid = {'n_estimators':[50, 100, 300, 500, 1000],

                       'min_samples_leaf': [1, 2, 4, 6, 8],

                       'min_samples_split': [2, 3, 5, 7, 9],

                       'max_features': ['auto', 'sqrt', 'log2', None]}

extra = ExtraTreesClassifier()

random = RandomizedSearchCV(extra, param_distributions=hyperparameter_grid,random_state=1)

In [77]:
random.fit(x_train_scaled,y_train)

RandomizedSearchCV(cv=None, error_score=nan,
                   estimator=ExtraTreesClassifier(bootstrap=False,
                                                  ccp_alpha=0.0,
                                                  class_weight=None,
                                                  criterion='gini',
                                                  max_depth=None,
                                                  max_features='auto',
                                                  max_leaf_nodes=None,
                                                  max_samples=None,
                                                  min_impurity_decrease=0.0,
                                                  min_impurity_split=None,
                                                  min_samples_leaf=1,
                                                  min_samples_split=2,
                                                  min_weight_fraction_leaf=0.0,
                                     

In [78]:
random.best_params_

{'max_features': None,
 'min_samples_leaf': 8,
 'min_samples_split': 2,
 'n_estimators': 1000}

In [80]:
random.best_estimator_

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features=None,
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=8, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=1000,
                     n_jobs=None, oob_score=False, random_state=None, verbose=0,
                     warm_start=False)

In [81]:
random.best_score_

0.9251250000000001

In [83]:
extra_predictions = random.predict(x_test_scaled)

In [84]:
cnf_mat = confusion_matrix(y_true=y_test, y_pred=extra_predictions,labels=['stable', 'unstable'])
cnf_mat

array([[ 620,   92],
       [  46, 1242]])

In [85]:
precision = precision_score(y_true=y_test, y_pred=extra_predictions, pos_label='stable')
print('Precision: {}'.format(round(precision*100), 2))

Precision: 93.0


In [86]:
recall = recall_score(y_true=y_test, y_pred=extra_predictions, pos_label='stable')
print('Recall: {}'.format(round(recall*100), 2))

Recall: 87.0


In [87]:
accuracy = accuracy_score(y_true=y_test, y_pred=extra_predictions)
print('Accuracy: {}'.format(round(accuracy*100), 2))

Accuracy: 93.0


In [88]:
f1 = f1_score(y_true=y_test, y_pred=extra_predictions, pos_label='stable')
print('F1: {}'.format(round(f1*100), 2))

F1: 90.0


In [102]:
print('Classifcation report for randomserch \n', classification_report(y_test, extra_predictions))

Classifcation report for randomserch 
               precision    recall  f1-score   support

      stable       0.93      0.87      0.90       712
    unstable       0.93      0.96      0.95      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.92      0.92      2000
weighted avg       0.93      0.93      0.93      2000



question1 

In [105]:
precison = 355/(355+1480)
precision

0.9309309309309309

In [108]:
recall = 355/(355+45)
recall

0.8875

In [112]:
((precision * recall)/(precision + recall))*2

0.9086968189418492

In [121]:
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.model_selection import RandomizedSearchCV


hyperparameter_grid1 = {'n_estimators':[50, 100, 300, 500, 1000],

                       'min_samples_leaf': [1, 2, 4, 6, 8],

                       'min_samples_split': [2, 3, 5, 7, 9],

                       'max_features': ['auto', 'sqrt', 'log2', None]}

extra1 = ExtraTreesClassifier()

random1 = RandomizedSearchCV(extra1, param_distributions=hyperparameter_grid1,random_state=1,cv=5, n_iter=10, scoring = 'accuracy', n_jobs = -1, verbose = 1)

In [122]:
random1.fit(x_train_scaled,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:  1.4min
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:  1.4min finished


RandomizedSearchCV(cv=5, error_score=nan,
                   estimator=ExtraTreesClassifier(bootstrap=False,
                                                  ccp_alpha=0.0,
                                                  class_weight=None,
                                                  criterion='gini',
                                                  max_depth=None,
                                                  max_features='auto',
                                                  max_leaf_nodes=None,
                                                  max_samples=None,
                                                  min_impurity_decrease=0.0,
                                                  min_impurity_split=None,
                                                  min_samples_leaf=1,
                                                  min_samples_split=2,
                                                  min_weight_fraction_leaf=0.0,
                                        

In [123]:
random1.best_params_

{'max_features': None,
 'min_samples_leaf': 8,
 'min_samples_split': 2,
 'n_estimators': 1000}

In [131]:
extra1_predictions = random1.predict(x_test_scaled)

In [133]:
print('Classification report for Extra with hydraparameters', classification_report(y_test, extra1_predictions))

Classification report for Extra with hydraparameters               precision    recall  f1-score   support

      stable       0.92      0.87      0.90       712
    unstable       0.93      0.96      0.94      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



In [126]:
feature_importances = random1.best_estimator_.feature_importances_
feature_importances

array([0.1380407 , 0.14058332, 0.13374718, 0.13497292, 0.00373281,
       0.00544679, 0.00531071, 0.00517451, 0.10256946, 0.10835397,
       0.11208669, 0.10998094])

In [135]:
from sklearn.ensemble import ExtraTreesClassifier
extra3 = ExtraTreesClassifier(random_state=1)
extra3.fit(x_train_scaled,y_train)
extra3_predictions = extra3.predict(x_test_scaled)

In [136]:
print('Classification report for with no hydraparameters', classification_report(y_test, extra3_predictions))

Classification report for with no hydraparameters               precision    recall  f1-score   support

      stable       0.94      0.85      0.89       712
    unstable       0.92      0.97      0.94      1288

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000

